### ISSUE TITLE
通过$set删除数组中的某一项，视图不能更新

### ISSUE THREAD

**Issue by StudentWan** [ecomfe/san-update#10]
任务里需要完成一个点击按钮之后删除列表中某一项的功能。
我的做法是在点击按钮后dispatch一个action
```
export default connect.san({}, {delete: 'deleteTodo'}) ({
    doDelete: function (index) {
            this.actions.delete(index)
    }
```

然后在`action.js`里面用返回`updateBuilder().set(...)`发现相应的视图并没有更新
用返回`updateBuilder().splice(...)`可以使视图更新，相应的代码如下：
```
store.addAction('deleteTodo', function (index) {
    let todos = store.getState('todos')
    todos.splice(index, 1)
    // return updateBuilder().set('todos', todos) 视图不会同步更新
    return updateBuilder().splice('todos', index, 1)
})
```

数据都是更新了的
但不知道为什么set不可以更新视图
特来请教大佬...

**Comment by asd123freedom** [comment]
我看文档的理解是 set 是用来改变属性值的，对于数组的改变，set 应该是不适合的。另外，不更新的原因我猜是自己 splice 之后再 set，引用应该不变，所以视图不更新吧。。。

**Comment by StudentWan** [comment]
@asd123freedom 
了解了~
我刚才也自己测试了一下，引用确实没有改变
重新attach之后改变了引用
具体的原理我再学习一下源码，谢谢！
